sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
services: mongodb
install:
  - pip install pkginfo<1.3
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
env:
  - ADAPTER=mongo
  - ADAPTER=tiny
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=story setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: cI2oXCuwClLj2sRRr5i9PMnfp0WC7gDbAnrWV9HFPvxwIzPQWLFxZrt78m+7uPDWCB65zPeMch6pwNc9Q+UFvVF3SF25ovfJTYuUHTdoHbIhjrYJPBI0C3ak5nvB0evjBvjJ3Efg/i7mG7KVSZO3imm/wF7BGAQysMR3vhfhVPTedpQ5J9oDy/pTvYrovgbubs5TO3eGIpk1mDFxSDPNxCOl5HJinC87oHF/7HmZ0r+UevHXHVxHSdkgS/DTKmcVrqpGxy0RGkAU5ZShjw4iQ0l+Uv5q7VD8X0JFeK7Z0s7xy+cg/Do/gDVn41VdmkRDDIfjAxsphTF2/97e5hDO9RcruVRX2lNg/AWC7PFFrcy9OH8DWMM0ilfZz/xTPcSsT7lu6Q9Pu4QdfLvFMLTojA/QTOQ4IfGQEGMZ+uyeQ+rtw/QTS6tT6yfEXjo0EhI5CJGxxHGQGhDJek3mCQh6RGH++TMr+3Us2IYvJqoH/nwTp9ccTzUN1/olsBZEQlvPwT/3A4nb4imMJP3GrCsfswAZ98tuNkedsih/fHUWaS+RJMuRxbsBVXracKCuUKeRAiyG/rFNxb6cU7AroplsSAEod3MVuHcItv8cqdbmcSRy5IrHAcmcKIb3NHHIHRevStAc0iG6fd05cRE1cMVFByqJZ2iW4+uW/Z7lfP439Lc=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
    condition: $ADAPTER = mongo
